### ISSUE TITLE
Qt5 import error Qt4 import error

### ISSUE THREAD

**Issue by smartm0use** [alandmoore/wcgbrowser#21]
I'm on Ubuntu and I'm trying to run browser (I had first to run `pip install pyyaml`), but I get the following error:

```
Qt5 import error
Qt4 import error
```

![Screenshot at 2019-10-27 16-01-11](https://user-images.githubusercontent.com/5399265/67636632-065c2200-f8d3-11e9-8e65-3d25e8ce7013.png)

How to fix it?

**Comment by alandmoore** [comment]
I think the only problem here is that the output from the program is confusing; this isn't really an "error", it's just that wcgbrowser attempts to run using PyQt5, PyQt4, and PySide.  It prints an "error" as it attempts to load each one.  The fact that it actually ran means it did find something to use.

As for the screenshot, that is as expected since you haven't passed in a configuration.
